name: Wake Streamlit App

on:
  schedule:
    # A cada 60 minutos
    - cron: "*/60 * * * *"
  workflow_dispatch:

jobs:
  wake:
    runs-on: ubuntu-latest
    steps:
      - name: Wake Streamlit
        run: |
          echo "Waking Streamlit App..."
          curl -I https://plasprint20.streamlit.app/
